### ISSUE TITLE
304 Exception calling RPC request: 'CorePlugin.uTorrentImport'

### ISSUE THREAD

**Issue by houdini3009** [Laharah/deluge-uTorrentImport#7]
I've installed Deluge on my Synology. Python 2.7 and Python 3 are both installed. When I'm logged into the box as root, "python --version" shows me 2.7. When I try to enable uTorrentImport, I get the following error:

```
[ERROR   ] 00:29:38 rpcserver:304 Exception calling RPC request: 'CorePlugin.uTorrentImport'
Traceback (most recent call last):
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/core/rpcserver.py", line 299, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/core/core.py", line 528, in enable_plugin
    self.pluginmanager.enable_plugin(plugin)
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/core/pluginmanager.py", line 82, in enable_plugin
    super(PluginManager, self).enable_plugin(name)
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/pluginmanagerbase.py", line 151, in enable_plugin
    component.start([instance.plugin._component_name])
  File "/usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.12-py2.7.egg/deluge/component.py", line 290, in start
    if self.components[name]._component_depend:
KeyError: 'CorePlugin.uTorrentImport'
```

**Comment by Laharah** [comment]
Hmmm, I'm not familiar with running deluge on a synology box, but I'll see if I can help. From the looks of that stack trace, deluge can't find the plugin to load it correctly. My first instinct is that the wrong .egg version is installed. You'll be needing the `uTorrentImport-x.x-py2.7.egg` egg from the [release](https://github.com/Laharah/deluge-uTorrentImport/releases/latest) page. 

If you're sure you've got the correct egg I'm a bit stumped, since it doesn't seem that any of my code is getting called before the error. Is there anything interesting before the error in the log? There should be a block with lines like "Found plugin: __ __ at __", is utorrentimport in there?

For some reason, it seems the plugin isn't registered with the component manager, this should be happening automatically when the plugin is loaded.

**Comment by Laharah** [comment]
I've pushed an attempt at a fix [here](https://github.com/Laharah/deluge-uTorrentImport/releases/tag/v2.3.1-beta). With this at least we should at least be able to tell if the error is in the deluge installation or in the plugin. Install those versions of the eggs and see if there's a log line that looks like `[uTorrentImport] initialized successfully...`, if there isn't we'll have to keep digging.

**Comment by houdini3009** [comment]
The beta does seem to resolve the error:

```
[INFO    ] 16:15:36 pluginmanagerbase:170 Plugin uTorrentImport disabled..
[INFO    ] 16:15:40 pluginmanagerbase:158 Plugin uTorrentImport enabled..
```

However, I still can't seem to access the web UI? Nothing shows up in the sidebar.

**Comment by Laharah** [comment]
Glad that first error is fixed, really weird.

Unfortunately, the plugin doesn't have a web UI. You'll have to use deluge in thin client mode if your synology is running deluge headlessly. There are instructions how to do that here: 

http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient

Keep in mind, the plugin will import your uTorrent files from the same machine where the "deluged" server is running, not necessarily the machine where you're running the client.
